### ISSUE TITLE
hex file for Afro 30A

### ISSUE THREAD

**Issue by papage** [mindnever/brushed-esc-firmware#1]
I would be a good idea, to have the hex file for the Afro 30A esc, in the repo. Most of us that we are not familiar with the devtools for the AVR, would need the hex file, in order to save time and effort. Some documentation for uploading the firmware would be nice too (or a link to it).

Thanx for your effort! Regards!
Spiros

**Comment by mindnever** [comment]
I have added now prebuilt hex for Afro 30A esc.
Please keep in mind that this is very simple esc implementation for brushed motors. It has no programmable features, and anything you want to change you need to change by rebuilding it.
Other than that, it works great :)

Uploading is easiest done with [4712 / BLHeliSuite](https://github.com/4712/BLHeliSuite/releases). Just connect to the esc and choose "Flash Other", then select the hex form this repo.

Connection to the brushed motor is done with two wires, using B and C terminals. A is not used for these motors.
Neutral input is by default 1500ms with +/- 50ms of dead-band around it.

**Comment by papage** [comment]
Thank you! You are awesome!

Happy Christmas,
Sp

**Comment by papage** [comment]
Hi,

Your firmware worked like a charm! It made a kid very happy!

Thanx!
Sp
